config/routes.rb
Rails.application.routes.draw do
  get 'pages/welcome'

  resources :phones


  Rails.application.routes.draw do


    root to: "pages#welcome"



    get "/phones" => "phones#index"




    end

end

app/models/phone.rb
class Phone < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def welcome
  end
  
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_action :set_phone, only: [:show, :edit, :update, :destroy]

  # GET /phones
  # GET /phones.json
  def index
    @phones = Phone.all
  end

  # GET /phones/1
  # GET /phones/1.json
  def show
  end

  # GET /phones/new
  def new
    @phone = Phone.new
  end

  # GET /phones/1/edit
  def edit
  end

  # POST /phones
  # POST /phones.json
  def create
    @phone = Phone.new(phone_params)

    respond_to do |format|
      if @phone.save
        format.html { redirect_to @phone, notice: 'Phone was successfully created.' }
        format.json { render :show, status: :created, location: @phone }
      else
        format.html { render :new }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phones/1
  # PATCH/PUT /phones/1.json
  def update
    respond_to do |format|
      if @phone.update(phone_params)
        format.html { redirect_to @phone, notice: 'Phone was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone }
      else
        format.html { render :edit }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phones/1
  # DELETE /phones/1.json
  def destroy
    @phone.destroy
    respond_to do |format|
      format.html { redirect_to phones_url, notice: 'Phone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone
      @phone = Phone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_params
      params.require(:phone).permit(:name, :brand, :photo_url, :price, :instock)
    end
end





# class PhonesController < ApplicationController
#
#   def index
#     @phones = Phone.all
#   end
#
#   def show
#     @phones = Phone.find(params[:id])
#   end
#
#   def new
#     @phones = Phone.new(instock: true)
#   end
#
#   def create
#     @phones = Phone.new(phone_params)
#     if @phones.save
#       redirect_to phone_path, notice: "New Phone Added"
#     else
#       render :new
#     end
#   end
#
#   def edit
#     @phones = Phone.find(params[:id])
#   end
#
#   def update
#     @phones = Phone.find(params[:id])
#     if @phones.update(phones_params)
#       redirect_to @phones, notice: "Phone Saved"
#     else
#       render :edit
#     end
#   end
#
#   def destroy
#     @phones = Phone.find(params[:id])
#     @phones.destroy
#     redirect_to phone_path, notice: "Phone Removed"
#   end
#
#   def phone_params
#
# params.require(:phone).permit(:name, :brand, :photo_url, :price, :instock)
#     end
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Phones</title>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/welcome.html.erb
<center>


<h1>Phone Search</h1>
<p>See the latest phones out there</p>


<%= link_to "phones" do %>

<%= image_tag "iphone6.jpg" %>

<p>
Click here to view phones</p>
<% end %>


</center>

app/views/phones/_form.html.erb
<%= form_for(@phone) do |f| %>
  <% if @phone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phone.errors.count, "error") %> prohibited this phone from being saved:</h2>

      <ul>
      <% @phone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_area :brand %>
  </div>
  <div class="field">
    <%= f.label :photo_url %><br>
    <%= f.text_field :photo_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_area :price %>
  </div>
  <div class="field">
    <%= f.label :instock %><br>
    <%= f.check_box :instock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phones/edit.html.erb
<h1>Editing phone</h1>

<%= render 'form' %>

<%= link_to 'Show', @phone %> |
<%= link_to 'Back', phones_path %>

app/views/phones/index.html.erb
<center>

  <h1>Listing phones</h1>

<%= link_to root_path do %>
<p> Home </p>
<% end %>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Brand</th>
      <th>Photo</th>
      <th>Price</th>
      <th>In Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<br />

  <tbody>
    <% @phones.each do |phone| %>
      <tr>
        <td><%= phone.name %></td>
        <td><%= phone.brand %></td>
        <td><%= image_tag phone.photo_url, class: 'thumb'%></td>
        <td><%= phone.price %></td>
        <td><%= phone.instock %></td>
        <td><%= link_to 'Show', phone %></td>
        <td><%= link_to 'Edit', edit_phone_path(phone) %></td>
        <td><%= link_to 'Remove', phone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phone', new_phone_path %>
</center>

app/views/phones/new.html.erb
<center>

<h1>New phone</h1>

<%= render 'form' %>

<%= link_to 'Back', phones_path %>


</center>

app/views/phones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @phone.name %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @phone.brand %>
</p>

<p>
  <strong>Photo url:</strong>
  <%= @phone.photo_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @phone.price %>
</p>

<p>
  <strong>Instock:</strong>
  <%= @phone.instock %>
</p>

<%= link_to 'Edit', edit_phone_path(@phone) %> |
<%= link_to 'Back', phones_path %>